import { assetUrl } from './asset-url';
import React, { useEffect, useRef, useState } from 'react';
import { PageMotion } from './PageMotion';
import { HeroProcess } from './HeroProcess';
import { HeroVariant } from './HeroVariant';
import { TaskExplorer } from './TaskExplorer';
import { FinancialImpact } from './FinancialImpact';
import { caseStudies, CaseStudies, CaseStudyDetail } from './CaseStudies';
import { LaunchProcess, DeliverySection, QualitySection } from './DeliverySections';
import { IntegrationsSection, FormatsSection, ResearchSection, FaqSection } from './ExpansionSections';
import { ArrowRight, ArrowUp, ArrowUpRight, CaretRight, ChatCircleDots, ChartBar, Check, CheckCircle, ClipboardText, Database, DownloadSimple, FileText, GearSix, MagnifyingGlass, List, Play, TelegramLogo, User, X } from '@phosphor-icons/react';

const products = [
{id:'manager',name:'ИИ-менеджер',icon:ChatCircleDots,image:'editorial-manager.png',description:'Уточняет запрос и готовит заявку для отдела продаж.',detail:'Помогает клиенту сформулировать задачу, собирает исходные данные и передаёт менеджеру содержание разговора.',input:'Здравствуйте! Нужен ИИ-помощник для обработки заявок с сайта.',steps:['Принимает входящий запрос','Уточняет задачу и собирает данные','Готовит заявку для менеджера'],result:'Заявка подготовлена',output:'Менеджер получает запрос клиента, историю диалога и список вопросов для следующего разговора.'},
{id:'content',name:'Контент-фабрика',icon:FileText,image:'editorial-content.png',description:'Готовит посты, сценарии и рассылки из вашей экспертизы.',detail:'Собирает повторяемый процесс выпуска контента: от интервью или записи до черновиков, которые проверяет редактор.',input:'Есть запись интервью об автоматизации бизнеса. Нужны пост, сценарий видео и письмо.',steps:['Разбирает исходный материал','Собирает идеи и структуру','Готовит черновики для редактора'],result:'Материалы готовы к проверке',output:'Редактор получает черновик поста, план видео и письмо на основе одного исходного материала.'},
{id:'assistant',name:'ИИ-помощник',icon:Database,image:'editorial-docs.png',description:'Находит ответы в документах компании.',detail:'Помогает сотрудникам находить нужные сведения в инструкциях и регламентах. Показывает источник, на который опирается ответ.',input:'Где найти порядок согласования коммерческого предложения?',steps:['Принимает вопрос сотрудника','Находит сведения в базе знаний','Показывает ответ с источником'],result:'Ответ найден в базе знаний',output:'Сотрудник видит инструкцию и ссылку на исходный документ. Сложный вопрос передаётся ответственному специалисту.'}
];
const navItems=[['Продукты','#products'],['Решения','#solutions'],['Кейсы','#projects'],['О нас','#about']];
function Brand({large=false}){return <a className={'brand'+(large?' brand-large':'')} href="#top" aria-label="ai-factory, на главную"><img src={assetUrl('brand-icon.png')} alt=""/><span><b>ai</b>-factory</span></a>}
function Button({children,onClick,href,secondary=false,dark=false,className='',...props}){const cls='button '+(secondary?'button-outline':dark?'button-dark':'button-lime')+' '+className;return href?<a className={cls} href={href} {...props}>{children}</a>:<button className={cls} onClick={onClick} {...props}>{children}</button>}
function ContactForm({initial={},headingId="dialog-title"}){
 const [values,setValues]=useState({name:'',contact:'',task:initial.task||'',interest:initial.interest||'Пока выбираю'}),[ready,setReady]=useState(false),[copied,setCopied]=useState(false),[copyError,setCopyError]=useState(false);
 const resultHeading=useRef(null);useEffect(()=>{if(ready)resultHeading.current?.focus()},[ready]);
 const brief='Бриф для ai-factory\n\nИмя: '+values.name.trim()+'\nКонтакт: '+values.contact.trim()+'\nИнтересует: '+values.interest+'\n\nЗадача:\n'+values.task.trim()+'\n';
 const update=e=>setValues(v=>({...v,[e.target.name]:e.target.value}));
 const download=()=>{const url=URL.createObjectURL(new Blob([brief],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='ai-factory-brief.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 const copy=async()=>{try{await navigator.clipboard.writeText(brief);setCopied(true);setCopyError(false)}catch{setCopyError(true)}};
 if(ready)return <div className="form-success"><CheckCircle size={56} weight="duotone" className="lime"/><p className="eyebrow">Всё собрано</p><h2 id={headingId} ref={resultHeading} tabIndex={-1}>Бриф подготовлен</h2><p>Сохраните его, чтобы обсудить проект с командой ai-factory.</p><div className="brief-preview"><span>{values.name}</span><strong>{values.interest}</strong><p>{values.task}</p></div><div className="modal-actions"><Button onClick={download}>Скачать бриф <DownloadSimple size={20}/></Button><Button secondary onClick={copy}>{copied?'Скопировано':'Скопировать'}{copied?<Check size={20}/>:<ClipboardText size={20}/>}</Button></div><p className="form-note" role="status">{copyError?'Не удалось скопировать. Скачайте бриф или выделите текст выше.':'В этом прототипе бриф сохраняется у вас. Заявка не отправлена.'}</p><button className="text-button" onClick={()=>{setReady(false);setCopied(false)}}>Изменить ответы</button></div>;
 return <><p className="eyebrow">Начнём знакомство</p><h2 id={headingId}>Что хотите поручить ИИ?</h2><p className="dialog-intro">Расскажите о задаче. Соберём короткий бриф, который можно сохранить для обсуждения.</p><form className="contact-form" onSubmit={e=>{e.preventDefault();setReady(true)}}><div className="form-row"><label>Как вас зовут<input name="name" value={values.name} onChange={update} placeholder="Ваше имя" autoComplete="name" required maxLength={80}/></label><label>Как с вами связаться<input name="contact" value={values.contact} onChange={update} placeholder="Telegram или почта" autoComplete="off" required maxLength={120}/></label></div><label>Что интересует<select name="interest" value={values.interest} onChange={update}><option>Пока выбираю</option>{products.map(p=><option key={p.id}>{p.name}</option>)}<option>Решение под мою задачу</option></select></label><label>Что команда сейчас делает вручную?<textarea name="task" value={values.task} onChange={update} placeholder="Например: отвечаем на одинаковые вопросы клиентов и переносим заявки в CRM" required minLength={10} maxLength={3000} rows={4}/></label><Button type="submit">Подготовить бриф <ArrowRight size={20}/></Button><p className="form-note">Бриф можно скачать или скопировать. Данные из этой формы никуда не отправляются.</p></form></>
}
function ProductDemo({product,onContact}){
 const [step,setStep]=useState(-1);useEffect(()=>{if(step>=0&&step<3){const t=setTimeout(()=>setStep(s=>s+1),850);return()=>clearTimeout(t)}},[step]);const finished=step===3;
 return <><p className="eyebrow">Интерактивный пример</p><h2 id="dialog-title">{product.name}</h2><p className="dialog-intro">{product.detail}</p><div className="demo-request"><span>Пример запроса</span><p>{product.input}</p></div><ol className="demo-steps">{product.steps.map((s,i)=><li key={s} className={step>i?'is-done':step===i?'is-working':''}><span className="step-symbol">{step>i?<Check size={18} weight="bold"/>:i+1}</span><span>{s}</span>{step===i&&<span className="working-label">В работе</span>}</li>)}</ol><div className={'demo-result'+(finished?' visible':'')} aria-live="polite">{finished&&<><CheckCircle size={25}/><div><strong>{product.result}</strong><p>{product.output}</p></div></>}</div><div className="modal-actions"><Button disabled={step>=0&&step<3} onClick={()=>setStep(0)}>{step>=0&&step<3?'Сценарий выполняется':finished?'Повторить пример':'Запустить пример'}<Play size={18} weight="fill"/></Button><button className="text-button" onClick={onContact}>Обсудить мою задачу <ArrowUpRight size={20}/></button></div><p className="form-note">Сценарий показан на демоданных. Для вашего проекта уточним источники, действия и интеграции.</p></>
}
export function App({heroVariant='cards'}){
 const [menuOpen,setMenuOpen]=useState(false),[modal,setModal]=useState(null);const dialog=useRef(null);const closeModal=()=>setModal(null);const openContact=(prefill={})=>setModal({type:'contact',initial:{interest:typeof prefill.interest==='string'?prefill.interest:'Пока выбираю',task:typeof prefill.task==='string'?prefill.task:''}});
 useEffect(()=>{const el=dialog.current;if(modal){if(!el.open)el.showModal();el.querySelector('.close-button')?.focus();document.body.style.overflow='hidden'}else{if(el.open)el.close();document.body.style.overflow=''}return()=>{document.body.style.overflow=''}},[modal]);
 return <>
 <PageMotion/>
 <a className="skip-link" href="#products">К содержимому</a>
 <header className="header container" id="top"><Brand/><nav aria-label="Главная навигация" className={menuOpen?'nav is-open':'nav'} id="main-nav">{navItems.map(([name,url])=><a href={url} key={url} onClick={()=>setMenuOpen(false)}>{name}</a>)}</nav><Button className="header-cta" onClick={openContact}>Обсудить задачу <ArrowRight size={20}/></Button><button className="menu-button" aria-controls="main-nav" aria-expanded={menuOpen} aria-label={menuOpen?'Закрыть меню':'Открыть меню'} onClick={()=>setMenuOpen(v=>!v)}>{menuOpen?<X size={27}/>:<List size={27}/>}</button></header>
 <main>
 <section className={`hero container${heroVariant === 'cards' ? '' : ' hero--alternative'}`} aria-labelledby="hero-title">
   {heroVariant === 'cards' ? <HeroProcess/> : <HeroVariant variant={heroVariant}/>}
   <div className="hero-copy"><span className="hero-tag">Прикладной ИИ для бизнеса</span><p className="hero-eyebrow">ИИ-агентство Макса Люшера</p><h1 id="hero-title">Больше времени.<br/> Больше прибыли.</h1><p className="hero-description">Внедряем ИИ в продажи, поддержку и контент. Считаем, какие расходы сократятся, сколько дополнительной маржи принесёт решение и когда окупится запуск.</p><div className="hero-actions"><Button onClick={openContact}>Обсудить задачу <ArrowRight size={20}/></Button><Button secondary href="#products">Готовые продукты</Button></div><a className="hero-economics-link" href="#economics">Рассчитать эффект в рублях <ArrowUpRight size={19}/></a></div>
 </section>
 <section id="solutions" className="solutions-section"><div className="container solutions-inner"><div><p className="eyebrow">Наш подход</p><h2>Что берём<br/> на себя</h2></div><div className="services">{[{title:'Посчитаем экономику',text:'Расходы, дополнительная маржа и окупаемость.'},{title:'Соберём ИИ-решение',text:'Агенты, автоматизация и интеграции.'},{title:'Проверим результат',text:'Сравним показатели до запуска и после.'}].map((s,i)=><article className="service" key={s.title}><span className="service-number">0{i+1}</span><div><h3>{s.title}</h3><p>{s.text}</p></div></article>)}</div></div></section>
 <TaskExplorer onChoose={openContact}/>
 <FinancialImpact onChoose={openContact}/>
 <section id="products" className="products-section"><div className="container"><div className="section-heading"><div><p className="eyebrow">Предлагаемая линейка</p><h2>Готовые продукты</h2></div><p>ИИ-решения, которые можно адаптировать под ваш бизнес.</p></div><div className="product-grid">{products.map(p=><article className="product-card" key={p.id}><img src={assetUrl(p.image)} alt={'Иллюстрация продукта «'+p.name+'»'} loading="lazy"/><div className="product-card-copy"><h3>{p.name}</h3><p>{p.description}</p><button className="scenario-link" onClick={()=>setModal({type:'product',id:p.id})} aria-label={'Смотреть сценарий: '+p.name}>Смотреть сценарий <ArrowRight size={21}/></button></div></article>)}</div></div></section>
 <IntegrationsSection onChoose={openContact}/>
 <CaseStudies onOpen={id=>setModal({type:"project",id})}/>
 <FormatsSection onChoose={openContact}/>
 <LaunchProcess/>
 <ResearchSection onChoose={openContact}/>
 <QualitySection/>
 <DeliverySection/>
 <section id="about" className="founder-section container"><div className="founder-photo"><img src={assetUrl('editorial-founder.png')} alt="Макс Люшер, основатель ai-factory" loading="lazy"/></div><div className="founder-copy"><p className="eyebrow">Основатель ai-factory</p><h2>Макс Люшер</h2><h3>Начнём с задач вашей команды.</h3><p>Выберем процесс, посчитаем возможный эффект<br className="desktop-break"/> и проверим его на ваших данных.<a className="founder-channel" href="https://t.me/+KnTNi1AANSIwNDY6" target="_blank" rel="noopener noreferrer"><TelegramLogo size={28} weight="fill" aria-hidden="true"/><span className="founder-channel-copy"><small>Канал про ИИ в Telegram</small><strong>Люшер в AI — избранное</strong></span><ArrowUpRight className="founder-channel-arrow" size={18} aria-hidden="true"/></a></p></div></section>
 <FaqSection onChoose={openContact}/>
 <section id="brief" className="brief-section"><div className="container brief-layout"><div className="brief-intro"><p className="eyebrow">Первый шаг</p><h2>Где бизнес<br/>теряет время<br/>и деньги?</h2><p>Опишите задачу и текущие расходы. Если цифр пока нет, начнём с одного рабочего примера и соберём исходные данные вместе.</p><ol><li><span>01</span>Опишите повторяющуюся задачу</li><li><span>02</span>Добавьте объём задач и расходы, если они известны</li><li><span>03</span>Сохраните бриф для обсуждения проекта</li></ol></div><div className="brief-form"><ContactForm headingId="brief-form-title"/></div></div></section>
 <section className="contact-strip"><div className="container contact-strip-inner"><img src={assetUrl('brand-icon.png')} alt=""/><h2>С какой задачи<br/>начнём?</h2><div className="contact-strip-action"><p>Расскажите, что команда<br/>сейчас делает вручную.</p><Button dark onClick={openContact}>Обсудить задачу <ArrowRight size={21}/></Button></div></div></section>
 </main>
 <footer className="footer-expanded container"><div className="footer-directory"><p>Прикладной ИИ для задач вашей команды.</p><div><h3>Решения</h3><nav aria-label="Решения в подвале"><a href="#tasks">Сценарии работы</a><a href="#products">Готовые продукты</a><a href="#integrations">Интеграции</a><a href="#research">Своя задача</a></nav></div><div><h3>Сотрудничество</h3><nav aria-label="Сотрудничество"><a href="#economics">Эффект в рублях</a><a href="#formats">Форматы работы</a><a href="#process">Этапы внедрения</a><a href="#handover">После запуска</a><a href="#brief">Бриф на проект</a></nav></div><div><h3>Агентство</h3><nav aria-label="Агентство"><a href="#projects">Модельные кейсы</a><a href="#about">Основатель</a><a href="#quality">Контроль качества</a><a href="#faq">Вопросы и ответы</a></nav></div></div><div className="footer"><Brand large/><div className="footer-meta"><a href="#top">Наверх <ArrowUp size={16}/></a><p>© 2026 ai-factory</p></div></div></footer>
 <dialog ref={dialog} className="modal" aria-labelledby="dialog-title" onCancel={closeModal} onClose={closeModal} onClick={e=>{if(e.target===e.currentTarget)closeModal()}}><div className="modal-controls"><button className="close-button" onClick={closeModal} aria-label="Закрыть окно"><X size={26}/></button></div><div className="modal-inner" onClick={e=>e.stopPropagation()}>{modal?.type==='contact'&&<ContactForm initial={modal.initial}/>}{modal?.type==='product'&&<ProductDemo key={modal.id} product={products.find(p=>p.id===modal.id)} onContact={()=>openContact({interest:products.find(p=>p.id===modal.id).name})}/ >}{modal?.type==='project'&&<CaseStudyDetail project={caseStudies.find(p=>p.id===modal.id)} onChoose={openContact}/>}</div></dialog>
 </>
}
